services:
  scheduler:
    build:
      context: .
      dockerfile: DOCKERFILE
      platforms:
        - linux/amd64
        - linux/arm64
    container_name: scheduler
    restart: always
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      - NODE_ENV=development
      - DB_HOST=host.docker.internal
      - BASE_DB_HOST=host.docker.internal
      - ADMIN_ERROR_UI=true
      - ADMIN_ALLOW_IPS=
    ports:
      - "8080:8080"
