# syntax=docker/dockerfile:1
FROM oven/bun:1 AS base
WORKDIR /usr/src/app

# install dependencies into temp directory
# this will cache them and speed up future builds
FROM base AS install
RUN mkdir -p /temp/dev
COPY package.json bun.lock /temp/dev/
RUN cd /temp/dev && bun install --frozen-lockfile
#RUN add-apt-repository universe

# install with --production (exclude devDependencies)
RUN mkdir -p /temp/prod
COPY package.json bun.lock /temp/prod/
RUN cd /temp/prod && bun install --frozen-lockfile --production

# copy node_modules from temp directory
# then copy all (non-ignored) project files into the image
FROM base AS prerelease
COPY --from=install /temp/dev/node_modules node_modules
COPY --exclude=src/UI . .

# [optional] tests & build
ENV NODE_ENV=development
# RUN bun test // tests are not implemented yet
RUN bun run build


FROM base AS ui
COPY src/UI/package.json src/UI/bun.lock ./
RUN bun install --frozen-lockfile
COPY src/UI/ ./
RUN bun run build


# copy production dependencies and source code into final image
FROM base AS release
ARG SYSTEM_VERSION_STRING

COPY --from=install /temp/prod/node_modules node_modules
COPY --from=prerelease /usr/src/app/. .
COPY --from=prerelease /usr/src/app/package.json .
COPY --from=ui /usr/src/app/dist ./src/UI/dist

RUN apt update
RUN bun install -g typescript
RUN bun install bun-types
RUN bun run build:types

ENV SYSTEM_VERSION_STRING=$SYSTEM_VERSION_STRING

# run the app
# USER bun # TODO Investigate usign the same user for docker, in order to not face permissions issues
EXPOSE 8080/tcp
ENTRYPOINT ["bun", "run", "src/index.ts", "--verbose-error-trace" ]
